spring:
  application:
    name: osint-web-app

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    com.ptbox.osint_web_app.client: DEBUG

frontend:
  url: ${FRONTEND_URL}

docker:
  amass:
    name: caffix/amass
    tag: latest
